# Model arguments
model_name_or_path: /inspire/ssd/project/sais-bio/public/hanchen/save/qwen2.5-math-1.5b_mix
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: ../save/laphaStar_0129_qwen2.5-math-1.5b_mix_grpo_rooth0_kl

# Training arguments
num_train_epochs: 8
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-6 # 1.0e-6 as in the deepseek math paper 5-e7 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
lr_scheduler_type: cosine
warmup_ratio: 0.05

# MTPO
depth: 6
breadth: 6
num_generations: 8
steps_per_generation: 8
num_sim: 24
prune_per: 8
num_pos_sim: 1
passk_threshold: 1.0
enable_thinking: false

beta: 1.0e-8
loss_type: grpo
value_head_type: linear

# vLLM
use_vllm: true
vllm_mode: server
vllm_server_host: 0.0.0.0
vllm_server_port: 8000
vllm_server_timeout: 60

max_prompt_length: 4096
max_completion_length: 1024
temperature: 0.7
repetition_penalty: 1.05
top_p: 0.8
top_k: 20

# Logging arguments
logging_strategy: steps
logging_steps: 1
report_to: "tensorboard"
save_strategy: "steps"
save_steps: 5
seed: 1022

# Hugging Face Hub 
push_to_hub: false

